/**
 * OpenClaw Adapter
 * 
 * Manages skill file directory for OpenClaw integration.
 * Creates and maintains skill definitions that OpenClaw can use.
 */

import * as fs from 'fs';
import * as path from 'path';

export interface OpenClawConfig {
  enabled: boolean;
  skill_dir: string;
}

export interface SkillDefinition {
  name: string;
  version: string;
  description: string;
  triggers: string[];
  actions: SkillAction[];
}

export interface SkillAction {
  name: string;
  description: string;
  parameters: SkillParameter[];
}

export interface SkillParameter {
  name: string;
  type: 'string' | 'number' | 'boolean';
  description: string;
  required: boolean;
}

const ECHO_NODE_SKILL: SkillDefinition = {
  name: 'echo-node',
  version: '1.0.0',
  description: 'Voice-controlled AI assistant with personality presets',
  triggers: [
    'voice_command',
    'wake_word',
    'text_command',
  ],
  actions: [
    {
      name: 'speak',
      description: 'Make Echo-Node speak the given text',
      parameters: [
        {
          name: 'text',
          type: 'string',
          description: 'Text to speak',
          required: true,
        },
        {
          name: 'voice',
          type: 'string',
          description: 'Voice preset to use',
          required: false,
        },
      ],
    },
    {
      name: 'change_personality',
      description: 'Change the active personality preset',
      parameters: [
        {
          name: 'personality',
          type: 'string',
          description: 'Personality name (hacker, seductive, butler, drill-sergeant, stoner-philosopher)',
          required: true,
        },
      ],
    },
    {
      name: 'get_status',
      description: 'Get current Echo-Node status',
      parameters: [],
    },
    {
      name: 'get_conversation_history',
      description: 'Get recent conversation turns',
      parameters: [
        {
          name: 'limit',
          type: 'number',
          description: 'Number of turns to retrieve',
          required: false,
        },
      ],
    },
  ],
};

export class OpenClawAdapter {
  private config: OpenClawConfig;
  private skillPath: string;
  private initialized = false;

  constructor(config: OpenClawConfig) {
    this.config = config;
    this.skillPath = path.join(config.skill_dir, 'echo-node');
  }

  /**
   * Check if OpenClaw integration is enabled
   */
  isEnabled(): boolean {
    return this.config.enabled;
  }

  /**
   * Initialize skill directory
   */
  async initialize(): Promise<boolean> {
    if (!this.config.enabled) {
      console.log('[OpenClaw] Integration disabled');
      return false;
    }

    try {
      await this.ensureSkillDirectory();
      await this.writeSkillFile();
      this.initialized = true;
      console.log(`[OpenClaw] Skill directory initialized: ${this.skillPath}`);
      return true;
    } catch (error) {
      console.error('[OpenClaw] Failed to initialize:', error);
      return false;
    }
  }

  /**
   * Ensure skill directory exists
   */
  private async ensureSkillDirectory(): Promise<void> {
    const skillDir = this.skillPath;
    
    if (!fs.existsSync(skillDir)) {
      fs.mkdirSync(skillDir, { recursive: true });
    }

    const skillYamlPath = path.join(skillDir, 'skill.yaml');
    
    if (!fs.existsSync(skillYamlPath)) {
      fs.writeFileSync(skillYamlPath, '');
    }
  }

  /**
   * Write skill definition file
   */
  private async writeSkillFile(): Promise<void> {
    const skillYamlPath = path.join(this.skillDir, 'skill.yaml');
    const skillYaml = this.generateSkillYaml(ECHO_NODE_SKILL);
    fs.writeFileSync(skillYamlPath, skillYaml, 'utf-8');
  }

  /**
   * Generate YAML from skill definition
   */
  private generateSkillYaml(skill: SkillDefinition): string {
    let yaml = `# Echo-Node Skill Definition
# Generated by Echo-Node Gateway

name: ${skill.name}
version: ${skill.version}
description: ${skill.description}

triggers:
`;
    for (const trigger of skill.triggers) {
      yaml += `  - ${trigger}\n`;
    }

    yaml += `\nactions:\n`;
    for (const action of skill.actions) {
      yaml += `  - name: ${action.name}\n`;
      yaml += `    description: ${action.description}\n`;
      yaml += `    parameters:\n`;
      for (const param of action.parameters) {
        yaml += `      - name: ${param.name}\n`;
        yaml += `        type: ${param.type}\n`;
        yaml += `        description: ${param.description}\n`;
        yaml += `        required: ${param.required}\n`;
      }
    }

    return yaml;
  }

  /**
   * Get skill directory path
   */
  get skillDir(): string {
    return this.skillPath;
  }

  /**
   * Check if skill is initialized
   */
  isInitialized(): boolean {
    return this.initialized;
  }

  /**
   * Update skill definition
   */
  async updateSkill(skill: Partial<SkillDefinition>): Promise<boolean> {
    if (!this.initialized) {
      console.warn('[OpenClaw] Skill not initialized');
      return false;
    }

    try {
      const updatedSkill = { ...ECHO_NODE_SKILL, ...skill };
      const skillYamlPath = path.join(this.skillDir, 'skill.yaml');
      const skillYaml = this.generateSkillYaml(updatedSkill);
      fs.writeFileSync(skillYamlPath, skillYaml, 'utf-8');
      console.log('[OpenClaw] Skill definition updated');
      return true;
    } catch (error) {
      console.error('[OpenClaw] Failed to update skill:', error);
      return false;
    }
  }

  /**
   * Get skill definition
   */
  getSkillDefinition(): SkillDefinition {
    return { ...ECHO_NODE_SKILL };
  }

  /**
   * Remove skill directory
   */
  async cleanup(): Promise<void> {
    if (!this.config.enabled || !this.initialized) {
      return;
    }

    try {
      if (fs.existsSync(this.skillPath)) {
        fs.rmSync(this.skillPath, { recursive: true, force: true });
        console.log('[OpenClaw] Skill directory removed');
      }
    } catch (error) {
      console.error('[OpenClaw] Failed to cleanup:', error);
    }
  }
}

/**
 * Create OpenClaw adapter instance
 */
export function createOpenClawAdapter(config: OpenClawConfig): OpenClawAdapter {
  return new OpenClawAdapter(config);
}

/**
 * Get default OpenClaw configuration
 */
export function getDefaultOpenClawConfig(): OpenClawConfig {
  return {
    enabled: false,
    skill_dir: '~/.openclaw/skills/echo-node',
  };
}
